{"Similar_Directories":[{"similar_paths":["c:\\users\\dan\\music\\2Pac"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\2Pac & Snoop Dog",
"c:\\users\\dan\\music\\2pac & Snoop Dogg",
"c:\\users\\dan\\music\\Snoop Dogg"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\2Pac"},
{"similar_paths":["c:\\users\\dan\\music\\2Pac and Jodeci"],
"use_path_override":"c:\\users\\dan\\music\\2Pac"},
{"similar_paths":["c:\\users\\dan\\music\\3 Doors Down"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\30 Seconds To Mars"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\311"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\3OH!3"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\50 Cent"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\50 Cent Eminem G-Unit"],
"use_path_override":"c:\\users\\dan\\music\\50 Cent"},
{"similar_paths":["c:\\users\\dan\\music\\50 Cent Feat_ Mobb Deep",
"c:\\users\\dan\\music\\50 Cent Feat_ Ne-Yo",
"c:\\users\\dan\\music\\50 Cent Feat_ R_ Kelly"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\50 Cent"},
{"similar_paths":["c:\\users\\dan\\music\\50 Cent_ Justin Timberlake",
"c:\\users\\dan\\music\\Justin Timberlake"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\50 Cent"},
{"similar_paths":["c:\\users\\dan\\music\\504 Boyz"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\69 Boyz"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\8-Mile SoundTrack"],
"use_path_override":"c:\\users\\dan\\music\\Eminem"},
{"similar_paths":["c:\\users\\dan\\music\\A$AP Rocky"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Aaliyah"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Aaron Lewis&Fred Durst"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ace Of Base"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Action Bronson"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Action Bronson & Joey Bada$$ F"],
"use_path_override":"c:\\users\\dan\\music\\Action Bronson"},
{"similar_paths":["c:\\users\\dan\\music\\Adam Sandler"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Adema"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Adema (Adema)"],
"use_path_override":"c:\\users\\dan\\music\\Adema"},
{"similar_paths":["c:\\users\\dan\\music\\Aerosmith"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\AFI"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Afroman"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ahmad_ Ras Kass & Saafir"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Akon"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Akon featuring Eminem"],
"use_path_override":"c:\\users\\dan\\music\\Akon"},
{"similar_paths":["c:\\users\\dan\\music\\Alan Jackson"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\ali featuring st_ lunatics"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Alice Cooper"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Alice In Chains"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Alien Antfarm"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Alvin & The Chipmunks"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ameritz - Tribute"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Andrea Bocelli"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ang\u00e9lique Kidjo"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Anotha Level"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Appocolyptica"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Aretha Franklin"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Avant"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Avenged Sevenfold"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\B-Legit"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bach"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Backbone"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bad Meets Evil"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Baha Men"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bassnectar"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bear Hands"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Benny Benassi"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Better Than Ezra"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Big Sean"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Big Tymers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Biggy Smalls"],
"use_path_override":"c:\\users\\dan\\music\\Notorious BIG"},
{"similar_paths":["c:\\users\\dan\\music\\Bill Withers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Billy Currington"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Billy Idol"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Black Eyed Peas"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Black Sabbath"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Black Street feat_ Dr_ Dre"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Blade"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Blink 182"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Blondie"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bloodhound Gang"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Blue Oyster Cult"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Blues Brothers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bob Dylan"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bob Marley"],
"use_path_override":"c:\\users\\dan\\music\\Bob Marley & The Wailers"},
{"similar_paths":["c:\\users\\dan\\music\\Bob Marley & The Wailers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bob Segar"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bon Jovi"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bone Crusher ft_ T_I_ & Killer"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bone Thugs"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bone Thugs N Harmony"],
"use_path_override":"c:\\users\\dan\\music\\Bone Thugs"},
{"similar_paths":["c:\\users\\dan\\music\\Boondock Saints",
"c:\\users\\dan\\music\\Boondock Saints Soundtrack"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Boys II Men",
"c:\\users\\dan\\music\\Boyz II Men"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Boys II Men"},
{"similar_paths":["c:\\users\\dan\\music\\Brantley Gilbert"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Breaking Benjamin"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bret Michaels"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\BT"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bubba Sparxxx"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Buckcherry"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bulletboys"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Bush"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Busta Rhymes"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Butthole Surfers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\B_o_B"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Cake"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Camron"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Cassidy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\CHAGE and ASKA"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chamillionaire"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chevelle"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chicago"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chingy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chris Brown feat_ Lil Wayne &"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chris Issac"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chris Jericho"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Christian"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Chuck D Introducing The Wreck"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Chyna"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Cinderella"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Clarance Carter"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Coolio"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Counting Crows"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Craig Mack"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Crazy Town"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Crossfade"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Cypress Hill"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\D'Lo Brown"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\D12"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Da Rule"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Daddy Yankee"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Darius Rucker"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Dave Matthews Band"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\David Banner"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Death Cab for Cutie"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Denaun"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Depeche Mode"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Derek and the Dominos"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Deuce"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Diddy"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Digital Underground"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Dilated Peoples"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Dion"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Dire Straits"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Dirty Heads"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Disturbed"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\DJ Felli Fel"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\DJ Khaled"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\DMX"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\DMX Feat_ Dyme"],
"use_path_override":"c:\\users\\dan\\music\\DMX"},
{"similar_paths":["c:\\users\\dan\\music\\DMX feat_ Funk Master Flex"],
"use_path_override":"c:\\users\\dan\\music\\DMX"},
{"similar_paths":["c:\\users\\dan\\music\\DMX Feat_ Sisq\u00f3"],
"use_path_override":"c:\\users\\dan\\music\\DMX"},
{"similar_paths":["c:\\users\\dan\\music\\Doctor Demento"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Domino"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Don McLean"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Drake"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Drop Kick Murphy's",
"c:\\users\\dan\\music\\Dropkick Murphys"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Drop Kick Murphy's"},
{"similar_paths":["c:\\users\\dan\\music\\Dru Hill"],
"use_path_override":"c:\\users\\dan\\music\\Sisq\u00f3"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre Feat_ D_O_C & Snoop Do"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre Feat_ Kevin Lewis_ Jew"],
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre feat_ Knoc-turn'al"],
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre Feat_ Kurupt_ RBX & Sn",
"c:\\users\\dan\\music\\Dr_ Dre Feat_ Kurupt_ RBX_ Rag"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre Feat_ Mary J_ Blige"],
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre Feat_ RBX & Colin Wolf",
"c:\\users\\dan\\music\\Dr_ Dre Feat_ RBX & Snoop Dogg",
"c:\\users\\dan\\music\\Dr_ Dre Feat_ RBX_ Snoop Dogg",
"c:\\users\\dan\\music\\Dr_ Dre Feat_ Snoop Dogg",
"c:\\users\\dan\\music\\Dr_ Dre Feat_ Snoop Dogg & Col",
"c:\\users\\dan\\music\\Dr_ Dre Feat_ Snoop Dogg & D_O"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Dr_ Dre Feat_ That Nigga Daz_"],
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Duran Duran"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Eagles"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\easy e"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\EDGE"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Electric Light Orchestra"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Elton John"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Elvis Presley"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Eminem"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Eminem & D12",
"c:\\users\\dan\\music\\Eminem & Dr_ Dre"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Eminem"},
{"similar_paths":["c:\\users\\dan\\music\\Eminem Feat_ 50 Cent & Dr_ Dre",
"c:\\users\\dan\\music\\Eminem Feat_ 50 Cent_ Loyd Ban"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Eminem"},
{"similar_paths":["c:\\users\\dan\\music\\Eminem Feat_ Gwen Stefani"],
"use_path_override":"c:\\users\\dan\\music\\Eminem"},
{"similar_paths":["c:\\users\\dan\\music\\Eminem Feat_ Kobe",
"c:\\users\\dan\\music\\Eminem Feat_ Lil Wayne",
"c:\\users\\dan\\music\\Eminem Feat_ P!nk",
"c:\\users\\dan\\music\\Eminem Feat_ Rihanna"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Eminem"},
{"similar_paths":["c:\\users\\dan\\music\\Eminem_ DMX_ Obie Trice"],
"use_path_override":"c:\\users\\dan\\music\\Eminem"},
{"similar_paths":["c:\\users\\dan\\music\\Eric Clapton"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Eric Serman ft_ Marvin Gay"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Evanescence",
"c:\\users\\dan\\music\\Evanscence"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Evanescence"},
{"similar_paths":["c:\\users\\dan\\music\\Everlast & House Of Pain"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Executioners"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fabulous & Nate Dogg"],
"use_path_override":"c:\\users\\dan\\music\\Nate Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Faith No More"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fall Out Boy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Family Force 5"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fat Joe"],
"use_path_override":"c:\\users\\dan\\music\\Ja Rule"},
{"similar_paths":["c:\\users\\dan\\music\\Filter"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Finger Eleven"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fishbone"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Five Finger Death Punch"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Flashdance"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Flo Rida"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Flobots"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\For Elise"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fort Minor"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Foster the People"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fountains of Wayne"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Foxy Brown"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Framing Hanley"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Frank Sinatra"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Freak Nasty"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Fun_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\G Tom Mac"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\G-Unit"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Gary Wright"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ghetto Boys"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ginuwine"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Gnarls Barkley"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Gorillaz"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Green Day"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Gun's N Roses",
"c:\\users\\dan\\music\\Guns & Roses",
"c:\\users\\dan\\music\\Guns 'N' Roses",
"c:\\users\\dan\\music\\Guns N' Roses"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Gun's N Roses"},
{"similar_paths":["c:\\users\\dan\\music\\H-Blockx"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Haddaway"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Hans Zimmer"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Harry Connick_ Jr_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Hatch & Perry"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Heart"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Hollywood Undead"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Hoobastank"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Hot Chocolate"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Howard Shore"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Huey Lewis"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Hulk Hogan"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Iamcompton"],
"use_path_override":"c:\\users\\dan\\music\\Dr_ Dre"},
{"similar_paths":["c:\\users\\dan\\music\\Ice Cube"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ice Cube & Mack 10"],
"use_path_override":"c:\\users\\dan\\music\\Ice Cube"},
{"similar_paths":["c:\\users\\dan\\music\\Ice Cube & Paul Oakenfold"],
"use_path_override":"c:\\users\\dan\\music\\Ice Cube"},
{"similar_paths":["c:\\users\\dan\\music\\Ice Cube and DMX"],
"use_path_override":"c:\\users\\dan\\music\\Ice Cube"},
{"similar_paths":["c:\\users\\dan\\music\\Il Nino",
"c:\\users\\dan\\music\\Ill Nino"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Il Nino"},
{"similar_paths":["c:\\users\\dan\\music\\ILoveMakonnen"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Incubus"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ini Kamoze"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Institute"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\IRC channel #MP3_Collective"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\J Geils Band"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\J-Kwon"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ja Rule Ft Vita And 01"],
"use_path_override":"c:\\users\\dan\\music\\Ja Rule"},
{"similar_paths":["c:\\users\\dan\\music\\Jace Everett"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jagged Edge ft_ Nelly"],
"use_path_override":"c:\\users\\dan\\music\\Nelly"},
{"similar_paths":["c:\\users\\dan\\music\\James Horner"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jason Aldean"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jason Derulo"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jay And Silent Bob Strike Back"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jay Z",
"c:\\users\\dan\\music\\Jay-Z"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Jay Z"},
{"similar_paths":["c:\\users\\dan\\music\\Jay-Z -f_ Jermaine Dupri"],
"use_path_override":"c:\\users\\dan\\music\\Jay Z"},
{"similar_paths":["c:\\users\\dan\\music\\Jay-Z and Linkin Park",
"c:\\users\\dan\\music\\Jay-Z and Linkin Park - Collis"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Jay Z"},
{"similar_paths":["c:\\users\\dan\\music\\Jay-Z_ Amil_ Ja-Rule"],
"use_path_override":"c:\\users\\dan\\music\\Jay Z"},
{"similar_paths":["c:\\users\\dan\\music\\JD_ Nate Dogg"],
"use_path_override":"c:\\users\\dan\\music\\Nate Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Jeezy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jeniffer Lopez & Ja Rule"],
"use_path_override":"c:\\users\\dan\\music\\Ja Rule"},
{"similar_paths":["c:\\users\\dan\\music\\Jeremih"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jessica Simpson feat Lil Bow W"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jim Brickman"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jim Carrey"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jim Jones"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jimi Hendrix"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jimmy Buffett"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Jimmy Eat World"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Joe"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Joe Budden"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Joe Budden feat_ Busta Rhymes"],
"use_path_override":"c:\\users\\dan\\music\\Joe Budden"},
{"similar_paths":["c:\\users\\dan\\music\\John Michael Montgomery"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\John Powel"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\John Williams"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Johnny Cash"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\joseph arthur"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Journey"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Juvenile"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\J_ Cole",
"c:\\users\\dan\\music\\J_Cole"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\J_ Cole"},
{"similar_paths":["c:\\users\\dan\\music\\K Camp"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\K7"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kansas"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kanye West"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kardinal Offishall"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kate Perry"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kendrick Lamar"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kenny G"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kenny Rogers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kid Cudi"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kid Ink"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kid Rock"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Klaus Badelt"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Korn"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Kurupt feat_ Daz"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\La Dispute"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\La Roux"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Led Zeppelin"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Lee Ann Rimes (Coyote Ugly)"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Like a G6"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Lil Durk"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Lil Jon"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Lil Jon & The East Side Boyz"],
"use_path_override":"c:\\users\\dan\\music\\Lil Jon"},
{"similar_paths":["c:\\users\\dan\\music\\Lil Jon feat_ Tyga"],
"use_path_override":"c:\\users\\dan\\music\\Lil Jon"},
{"similar_paths":["c:\\users\\dan\\music\\Lil Kim feat_ 50 Cent"],
"use_path_override":"c:\\users\\dan\\music\\Lil' Kim"},
{"similar_paths":["c:\\users\\dan\\music\\Lil Wayne",
"c:\\users\\dan\\music\\Lil Zane",
"c:\\users\\dan\\music\\Lil' Wayne"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Lil Wayne"},
{"similar_paths":["c:\\users\\dan\\music\\Lil' Kim"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Limp Bizkit"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Linda Ronstadt"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Linkin Park",
"c:\\users\\dan\\music\\Linkin Park & Jay Z"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Linkin Park"},
{"similar_paths":["c:\\users\\dan\\music\\Live"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\LL Cool J"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Lloyd Banks"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Loverboy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ludacris"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ludacris feat_ Nate Dogg"],
"use_path_override":"c:\\users\\dan\\music\\Ludacris"},
{"similar_paths":["c:\\users\\dan\\music\\Luke Bryan"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Lynyrd Skynyrd"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\L_A_ Leakers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Macklemore & Ryan Lewis"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Makaveli"],
"use_path_override":"c:\\users\\dan\\music\\2Pac"},
{"similar_paths":["c:\\users\\dan\\music\\Mankind"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Marilyn Manson",
"c:\\users\\dan\\music\\Marylin Manson"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Marilyn Manson"},
{"similar_paths":["c:\\users\\dan\\music\\Marilyn&Sneaker Pimps"],
"use_path_override":"c:\\users\\dan\\music\\Marilyn Manson"},
{"similar_paths":["c:\\users\\dan\\music\\Mark Morrison"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mark's & Henry's"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Marky Mark"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Martina McBride"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mary J Blige ft Jadakiss  Fabo"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mase",
"c:\\users\\dan\\music\\Muse"],
"had_similar":true,
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Massive Attack"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Matisyahu"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\MC Hammer"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\MC Hammer Feat_ Deion Sanders"],
"use_path_override":"c:\\users\\dan\\music\\MC Hammer"},
{"similar_paths":["c:\\users\\dan\\music\\Meek Mill"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Meet Joe Black"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Meg Myers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Metallica"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\MGMT"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Michael Bubl\u00e9"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Michael Jackson"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mickey Avalon"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Middle Class Rut"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mobb Deep"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Moby"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mos Def and Pharoahe Monch (ft"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Movie Sounds Unlimited"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Movie Themes"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\mozart"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mr_ Ass"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\Mr_Cheeks f_ Missy and Puffy"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\MS MR"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mudvayne"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\My Darkest Days"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Mystikal"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\M_I_A_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Nas"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Nas ft_ Braveheartz"],
"use_path_override":"c:\\users\\dan\\music\\Nas"},
{"similar_paths":["c:\\users\\dan\\music\\Nate Dogg - Music & Me"],
"use_path_override":"c:\\users\\dan\\music\\Nate Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Nate Dogg f_ Fabolous"],
"use_path_override":"c:\\users\\dan\\music\\Nate Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Neil Diamond"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Neil Young"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Nelly",
"c:\\users\\dan\\music\\Nelly Feat_ Lil' Wayne"],
"use_path_override":"c:\\users\\dan\\music\\Nelly"},
{"similar_paths":["c:\\users\\dan\\music\\Nelly & The St_ Lunatics"],
"use_path_override":"c:\\users\\dan\\music\\Nelly"},
{"similar_paths":["c:\\users\\dan\\music\\Nelly & The Teamsters"],
"use_path_override":"c:\\users\\dan\\music\\Nelly"},
{"similar_paths":["c:\\users\\dan\\music\\Nelly Feat_ Cedric The Enterta"],
"use_path_override":"c:\\users\\dan\\music\\Nelly"},
{"similar_paths":["c:\\users\\dan\\music\\Nelly Feat_ Murphy Lee & Ali"],
"use_path_override":"c:\\users\\dan\\music\\Nelly"},
{"similar_paths":["c:\\users\\dan\\music\\Nerd"],
"use_path_override":"c:\\users\\dan\\music\\N_E_R_D_"},
{"similar_paths":["c:\\users\\dan\\music\\Nickelback",
"c:\\users\\dan\\music\\Nickleback"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Nickelback"},
{"similar_paths":["c:\\users\\dan\\music\\Nine Inch Nails"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Nirvana"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Notorious BIG",
"c:\\users\\dan\\music\\The Notorious B_I_G_"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Notorious BIG"},
{"similar_paths":["c:\\users\\dan\\music\\NWA"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\N_E_R_D_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Oakenfold"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Obie Trice"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Offspring",
"c:\\users\\dan\\music\\The Offspring"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\The Offspring"},
{"similar_paths":["c:\\users\\dan\\music\\Old Dirty Bastard"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Orchestra On The Half Shell"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Orgy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Original Soundtrack"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\OutKast"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Panic At the Disco",
"c:\\users\\dan\\music\\Panic! At the Disco"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Panic! At the Disco"},
{"similar_paths":["c:\\users\\dan\\music\\Papa Roach"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Paris"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Pendulum"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Peter Bjorn and John"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Peter Frampton"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Petey Pablo"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Phil Collins"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Pink Floyd"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Pitbull"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Plain White T's"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\POD",
"c:\\users\\dan\\music\\P_O_D",
"c:\\users\\dan\\music\\P_O_D_"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\POD"},
{"similar_paths":["c:\\users\\dan\\music\\Pretty Ricky"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\PRhyme Feat_ Logic"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Prince"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Puddle of Mudd"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Puff Daddy & Faith feat_ 112"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Puff Daddy & The Family"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Puff Daddy Feat_ R_kelly"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Puff Daddy ft_ Nas"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Puff Daddy_ Lil' Kim_ Notoriou"],
"use_path_override":"c:\\users\\dan\\music\\Puff Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Pulp Fiction"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Punjabi MC feat_ Jay-Z"],
"use_path_override":"c:\\users\\dan\\music\\Jay Z"},
{"similar_paths":["c:\\users\\dan\\music\\Pussycat Dolls",
"c:\\users\\dan\\music\\The Pussycat Dolls"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\The Pussycat Dolls"},
{"similar_paths":["c:\\users\\dan\\music\\Queen"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rage Against The Machine"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rally Ral"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rammstein"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rascal Flats"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Red Hot Chili Peppers"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Redman"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\REDMAN & METHODMAN"],
"use_path_override":"c:\\users\\dan\\music\\Redman"},
{"similar_paths":["c:\\users\\dan\\music\\Rhino Bucket"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rich Gang"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rick Ross"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rihanna"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rise Against"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rob Bailey & The Hustle Standa"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rob Zombie"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rocky Theme"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rolling Stones",
"c:\\users\\dan\\music\\The Rolling Stones"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\The Rolling Stones"},
{"similar_paths":["c:\\users\\dan\\music\\Rosemary Clooney"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Royal Crown Revue"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Run DMC"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rusted Root"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Rustic Overtones"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\R_ Kelly And Jay-Z"],
"use_path_override":"c:\\users\\dan\\music\\Jay Z"},
{"similar_paths":["c:\\users\\dan\\music\\R_E_M_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\R_O_S_C_K_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sauf Keita"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Scarface"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\ScHoolboy Q"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sean Kingston"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sean Paul"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Seether"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Shop Boyz"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sick Puppies"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\SinVamp5-Stray Cats"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sisq\u00f3"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sixx_A_M_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Skee-Lo"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Skrillex"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Slaughterhouse"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Smash Mouth"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Smashing Pumpkins"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Smoke DZA"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Snoop"],
"use_path_override":"c:\\users\\dan\\music\\Snoop Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Snoop Dogg & Wiz Khalifa"],
"use_path_override":"c:\\users\\dan\\music\\Snoop Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Snoop Doggy Dog & Dr_ Dre",
"c:\\users\\dan\\music\\Snoop Doggy Dogg-Warren G"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Snoop Dogg"},
{"similar_paths":["c:\\users\\dan\\music\\Soundtrack",
"c:\\users\\dan\\music\\~Soundtrack"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Spineshank"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Spose"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Staind"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\StarWars"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Steppenwolf"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Steve Miller Band"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Stone Sour"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sublime"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sum 41"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Susan Boyd"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Suzanne Vega"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Sygnal To Noise"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tag Team"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tears for Fears"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tech N9ne"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tenacious D"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tes-A-T"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tesla"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Band"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Big Show"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Black Keys"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Bravery",
"c:\\users\\dan\\music\\The Fray"],
"had_similar":true,
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Brian Setzer Orchestra"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The B_U_M_S"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Colony"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Corporation"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\The Four Tops"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Game"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Lonely Island"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Neighbourhood"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Pharcyde"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Police"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Presidents Of The United S"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Qemists"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Roots",
"c:\\users\\dan\\music\\The Roots and BT"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\The Roots"},
{"similar_paths":["c:\\users\\dan\\music\\The Sounds Of Garth Brooks"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Weeknd"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\The Who"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Theory of a Deadman"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Third Eye Blind"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\THIRTY SECONDS TO MARS"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Three Days Grace"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Three Six Mafia"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tia Carrere"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tim Mcgraw"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Timbaland"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tone-Loc"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tony Yayo"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tony! Toni! Ton\u00e9!"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Too $hort"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Toploader"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Trey Songz"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Tribal Ink"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Trick Daddy"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Trick Daddy f_ Lil John & Twis"],
"use_path_override":"c:\\users\\dan\\music\\Trick Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Trick Trick & Eminem"],
"use_path_override":"c:\\users\\dan\\music\\Trick Daddy"},
{"similar_paths":["c:\\users\\dan\\music\\Tupac"],
"use_path_override":"c:\\users\\dan\\music\\2Pac"},
{"similar_paths":["c:\\users\\dan\\music\\Tyga"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\T_I_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\T_O_K_"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\U2"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Under-Taker"],
"use_path_override":"c:\\users\\dan\\music\\WWF"},
{"similar_paths":["c:\\users\\dan\\music\\UNH Pimpin"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Unknown"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Usher"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Vanessa Williams"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Vanilla Ice"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Various Artists"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Wale"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Warren G & Mack 10"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Wayne & Garth"],
"use_path_override":"c:\\users\\dan\\music\\Soundtrack"},
{"similar_paths":["c:\\users\\dan\\music\\Whitney Houston"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Will Smith"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Wiz Khalifa"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\WWF"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Xscape"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Yanni"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Yelawolf"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\YG"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Ying Yang Twins"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Young Money"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\Zac Brown Band"],
"use_path_override":null},
{"similar_paths":["c:\\users\\dan\\music\\ZZ Top",
"c:\\users\\dan\\music\\ZZTop"],
"had_similar":true,
"use_path_override":"c:\\users\\dan\\music\\ZZ Top"}]